### ISSUE TITLE
删除的图片不能在继续添加

### ISSUE THREAD

**Issue by yksmile007** [watson-yan/vue-uploader#1]

**Comment by watson-yan** [comment]
只设置了不能添加重复的图片，这边测试了删除某张图片后再次添加时没有问题的

**Comment by yksmile007** [comment]
可以添加重复的图片啊，当你选中1.jpg,2.jpg,3.jpg添加上之后，再去选1.jpg还是可以选的，我这边只是运行了你的代码，还有就是删除图片1.jpg，立即再添加图片1.jpg就是添加不上

**Comment by watson-yan** [comment]
我明白了你的意思了，造成这个的原因是：触发上传事件只是在input[type='file']元素的onchange事件，由于你添加了1.jpg, 然后删除1.jpg,再添加1.jpg。 其实在input标签里选中的还是1.jpg 也就触发不了onchange事件，所以会导致上传不成功

**Comment by yksmile007** [comment]
怎么会触发不了onchange事件？我只要添加不就触发了onchange事件吗？
还有就是这个问题怎么解决？求解？

**Comment by watson-yan** [comment]
input[type='file']这个标签你添加文件的时候，其实它就绑定了一个你选中文件的路径，由于没有清空input[type='file']的选中项, 你再次添加相同文件的时候，由于路径是相同的，并不会产生onchange事件，
这个Issue我这两天忙完手头工作将会更新，谢谢关注。

**Comment by watson-yan** [comment]
已经修复了这个问题

**Comment by yksmile007** [comment]
还有就是可以添加相同的图片，这也是个问题
